### ISSUE TITLE
Publish on PowershellGallery

### ISSUE THREAD

**Issue by felixfbecker** [PrateekKumarSingh/Graphical#2]
Would be great to have this installable through `Install-Module`

**Comment by PrateekKumarSingh** [comment]
Sure @felixfbecker, I was working on an update, which has been delayed a bit, once the code is committed I'll publish the module on PowerShell Gallery too.

**Comment by PrateekKumarSingh** [comment]
On PowerShell Gallery now!

**Comment by PrateekKumarSingh** [comment]
closing this issue
